/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as MainRouteRouteImport } from './routes/_main/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as MainDashboardRouteImport } from './routes/_main/dashboard'
import { Route as MainSettingsRouteRouteImport } from './routes/_main/settings/route'
import { Route as MainUsersIndexRouteImport } from './routes/_main/users/index'
import { Route as MainTeamsIndexRouteImport } from './routes/_main/teams/index'
import { Route as MainUsersCreateRouteImport } from './routes/_main/users/create'
import { Route as MainSettingsTeamRouteImport } from './routes/_main/settings/team'
import { Route as MainSettingsProfileRouteImport } from './routes/_main/settings/profile'
import { Route as MainUsersUserIdIndexRouteImport } from './routes/_main/users/$userId/index'
import { Route as MainUsersUserIdEditRouteImport } from './routes/_main/users/$userId/edit'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRouteRoute = MainRouteRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const MainDashboardRoute = MainDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainSettingsRouteRoute = MainSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainUsersIndexRoute = MainUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainTeamsIndexRoute = MainTeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainUsersCreateRoute = MainUsersCreateRouteImport.update({
  id: '/users/create',
  path: '/users/create',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainSettingsTeamRoute = MainSettingsTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => MainSettingsRouteRoute,
} as any)
const MainSettingsProfileRoute = MainSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MainSettingsRouteRoute,
} as any)
const MainUsersUserIdIndexRoute = MainUsersUserIdIndexRouteImport.update({
  id: '/users/$userId/',
  path: '/users/$userId/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainUsersUserIdEditRoute = MainUsersUserIdEditRouteImport.update({
  id: '/users/$userId/edit',
  path: '/users/$userId/edit',
  getParentRoute: () => MainRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/settings': typeof MainSettingsRouteRouteWithChildren
  '/dashboard': typeof MainDashboardRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/settings/profile': typeof MainSettingsProfileRoute
  '/settings/team': typeof MainSettingsTeamRoute
  '/users/create': typeof MainUsersCreateRoute
  '/teams': typeof MainTeamsIndexRoute
  '/users': typeof MainUsersIndexRoute
  '/users/$userId/edit': typeof MainUsersUserIdEditRoute
  '/users/$userId': typeof MainUsersUserIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/settings': typeof MainSettingsRouteRouteWithChildren
  '/dashboard': typeof MainDashboardRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/settings/profile': typeof MainSettingsProfileRoute
  '/settings/team': typeof MainSettingsTeamRoute
  '/users/create': typeof MainUsersCreateRoute
  '/teams': typeof MainTeamsIndexRoute
  '/users': typeof MainUsersIndexRoute
  '/users/$userId/edit': typeof MainUsersUserIdEditRoute
  '/users/$userId': typeof MainUsersUserIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_main': typeof MainRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/_main/settings': typeof MainSettingsRouteRouteWithChildren
  '/_main/dashboard': typeof MainDashboardRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/_main/settings/profile': typeof MainSettingsProfileRoute
  '/_main/settings/team': typeof MainSettingsTeamRoute
  '/_main/users/create': typeof MainUsersCreateRoute
  '/_main/teams/': typeof MainTeamsIndexRoute
  '/_main/users/': typeof MainUsersIndexRoute
  '/_main/users/$userId/edit': typeof MainUsersUserIdEditRoute
  '/_main/users/$userId/': typeof MainUsersUserIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/settings'
    | '/dashboard'
    | '/auth/login'
    | '/auth/register'
    | '/settings/profile'
    | '/settings/team'
    | '/users/create'
    | '/teams'
    | '/users'
    | '/users/$userId/edit'
    | '/users/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/settings'
    | '/dashboard'
    | '/auth/login'
    | '/auth/register'
    | '/settings/profile'
    | '/settings/team'
    | '/users/create'
    | '/teams'
    | '/users'
    | '/users/$userId/edit'
    | '/users/$userId'
  id:
    | '__root__'
    | '/'
    | '/_main'
    | '/auth'
    | '/_main/settings'
    | '/_main/dashboard'
    | '/auth/login'
    | '/auth/register'
    | '/_main/settings/profile'
    | '/_main/settings/team'
    | '/_main/users/create'
    | '/_main/teams/'
    | '/_main/users/'
    | '/_main/users/$userId/edit'
    | '/_main/users/$userId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MainRouteRoute: typeof MainRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_main/dashboard': {
      id: '/_main/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof MainDashboardRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/settings': {
      id: '/_main/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof MainSettingsRouteRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/users/': {
      id: '/_main/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof MainUsersIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/teams/': {
      id: '/_main/teams/'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof MainTeamsIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/users/create': {
      id: '/_main/users/create'
      path: '/users/create'
      fullPath: '/users/create'
      preLoaderRoute: typeof MainUsersCreateRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/settings/team': {
      id: '/_main/settings/team'
      path: '/team'
      fullPath: '/settings/team'
      preLoaderRoute: typeof MainSettingsTeamRouteImport
      parentRoute: typeof MainSettingsRouteRoute
    }
    '/_main/settings/profile': {
      id: '/_main/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof MainSettingsProfileRouteImport
      parentRoute: typeof MainSettingsRouteRoute
    }
    '/_main/users/$userId/': {
      id: '/_main/users/$userId/'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof MainUsersUserIdIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/users/$userId/edit': {
      id: '/_main/users/$userId/edit'
      path: '/users/$userId/edit'
      fullPath: '/users/$userId/edit'
      preLoaderRoute: typeof MainUsersUserIdEditRouteImport
      parentRoute: typeof MainRouteRoute
    }
  }
}

interface MainSettingsRouteRouteChildren {
  MainSettingsProfileRoute: typeof MainSettingsProfileRoute
  MainSettingsTeamRoute: typeof MainSettingsTeamRoute
}

const MainSettingsRouteRouteChildren: MainSettingsRouteRouteChildren = {
  MainSettingsProfileRoute: MainSettingsProfileRoute,
  MainSettingsTeamRoute: MainSettingsTeamRoute,
}

const MainSettingsRouteRouteWithChildren =
  MainSettingsRouteRoute._addFileChildren(MainSettingsRouteRouteChildren)

interface MainRouteRouteChildren {
  MainSettingsRouteRoute: typeof MainSettingsRouteRouteWithChildren
  MainDashboardRoute: typeof MainDashboardRoute
  MainUsersCreateRoute: typeof MainUsersCreateRoute
  MainTeamsIndexRoute: typeof MainTeamsIndexRoute
  MainUsersIndexRoute: typeof MainUsersIndexRoute
  MainUsersUserIdEditRoute: typeof MainUsersUserIdEditRoute
  MainUsersUserIdIndexRoute: typeof MainUsersUserIdIndexRoute
}

const MainRouteRouteChildren: MainRouteRouteChildren = {
  MainSettingsRouteRoute: MainSettingsRouteRouteWithChildren,
  MainDashboardRoute: MainDashboardRoute,
  MainUsersCreateRoute: MainUsersCreateRoute,
  MainTeamsIndexRoute: MainTeamsIndexRoute,
  MainUsersIndexRoute: MainUsersIndexRoute,
  MainUsersUserIdEditRoute: MainUsersUserIdEditRoute,
  MainUsersUserIdIndexRoute: MainUsersUserIdIndexRoute,
}

const MainRouteRouteWithChildren = MainRouteRoute._addFileChildren(
  MainRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MainRouteRoute: MainRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
