/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as MainRouteRouteImport } from './routes/_main/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as MainDashboardRouteImport } from './routes/_main/dashboard'
import { Route as MainUsersRouteRouteImport } from './routes/_main/users/route'
import { Route as MainTeamsRouteRouteImport } from './routes/_main/teams/route'
import { Route as MainSettingsRouteRouteImport } from './routes/_main/settings/route'
import { Route as MainSettingsTeamRouteImport } from './routes/_main/settings/team'
import { Route as MainSettingsProfileRouteImport } from './routes/_main/settings/profile'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRouteRoute = MainRouteRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const MainDashboardRoute = MainDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainUsersRouteRoute = MainUsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainTeamsRouteRoute = MainTeamsRouteRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainSettingsRouteRoute = MainSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainSettingsTeamRoute = MainSettingsTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => MainSettingsRouteRoute,
} as any)
const MainSettingsProfileRoute = MainSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MainSettingsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/settings': typeof MainSettingsRouteRouteWithChildren
  '/teams': typeof MainTeamsRouteRoute
  '/users': typeof MainUsersRouteRoute
  '/dashboard': typeof MainDashboardRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/settings/profile': typeof MainSettingsProfileRoute
  '/settings/team': typeof MainSettingsTeamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/settings': typeof MainSettingsRouteRouteWithChildren
  '/teams': typeof MainTeamsRouteRoute
  '/users': typeof MainUsersRouteRoute
  '/dashboard': typeof MainDashboardRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/settings/profile': typeof MainSettingsProfileRoute
  '/settings/team': typeof MainSettingsTeamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_main': typeof MainRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/_main/settings': typeof MainSettingsRouteRouteWithChildren
  '/_main/teams': typeof MainTeamsRouteRoute
  '/_main/users': typeof MainUsersRouteRoute
  '/_main/dashboard': typeof MainDashboardRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/_main/settings/profile': typeof MainSettingsProfileRoute
  '/_main/settings/team': typeof MainSettingsTeamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/settings'
    | '/teams'
    | '/users'
    | '/dashboard'
    | '/auth/login'
    | '/auth/register'
    | '/settings/profile'
    | '/settings/team'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/settings'
    | '/teams'
    | '/users'
    | '/dashboard'
    | '/auth/login'
    | '/auth/register'
    | '/settings/profile'
    | '/settings/team'
  id:
    | '__root__'
    | '/'
    | '/_main'
    | '/auth'
    | '/_main/settings'
    | '/_main/teams'
    | '/_main/users'
    | '/_main/dashboard'
    | '/auth/login'
    | '/auth/register'
    | '/_main/settings/profile'
    | '/_main/settings/team'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MainRouteRoute: typeof MainRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_main/dashboard': {
      id: '/_main/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof MainDashboardRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/users': {
      id: '/_main/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof MainUsersRouteRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/teams': {
      id: '/_main/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof MainTeamsRouteRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/settings': {
      id: '/_main/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof MainSettingsRouteRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/settings/team': {
      id: '/_main/settings/team'
      path: '/team'
      fullPath: '/settings/team'
      preLoaderRoute: typeof MainSettingsTeamRouteImport
      parentRoute: typeof MainSettingsRouteRoute
    }
    '/_main/settings/profile': {
      id: '/_main/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof MainSettingsProfileRouteImport
      parentRoute: typeof MainSettingsRouteRoute
    }
  }
}

interface MainSettingsRouteRouteChildren {
  MainSettingsProfileRoute: typeof MainSettingsProfileRoute
  MainSettingsTeamRoute: typeof MainSettingsTeamRoute
}

const MainSettingsRouteRouteChildren: MainSettingsRouteRouteChildren = {
  MainSettingsProfileRoute: MainSettingsProfileRoute,
  MainSettingsTeamRoute: MainSettingsTeamRoute,
}

const MainSettingsRouteRouteWithChildren =
  MainSettingsRouteRoute._addFileChildren(MainSettingsRouteRouteChildren)

interface MainRouteRouteChildren {
  MainSettingsRouteRoute: typeof MainSettingsRouteRouteWithChildren
  MainTeamsRouteRoute: typeof MainTeamsRouteRoute
  MainUsersRouteRoute: typeof MainUsersRouteRoute
  MainDashboardRoute: typeof MainDashboardRoute
}

const MainRouteRouteChildren: MainRouteRouteChildren = {
  MainSettingsRouteRoute: MainSettingsRouteRouteWithChildren,
  MainTeamsRouteRoute: MainTeamsRouteRoute,
  MainUsersRouteRoute: MainUsersRouteRoute,
  MainDashboardRoute: MainDashboardRoute,
}

const MainRouteRouteWithChildren = MainRouteRoute._addFileChildren(
  MainRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MainRouteRoute: MainRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
